# Generated by Django 5.0.1 on 2024-02-06 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropmapp', '0002_schemeadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(blank=True, max_length=150, null=True)),
                ('eqipment_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_available', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
