# Generated by Django 4.2.5 on 2024-02-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropmapp', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
