# Generated by Django 5.0.2 on 2024-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropmapp', '0010_remove_order_razorpay_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerProduct',
        ),
    ]
