# Generated by Django 4.2.5 on 2024-02-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cropmapp', '0013_farmcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcart',
            name='total',
        ),
    ]
